### ISSUE TITLE
What is the current status of this project?

### ISSUE THREAD

**Issue by xiaoxiangmoe** [znck/vue-developer-experience#15]
Vue's TypeScript support needs to be improved. What do we need to do now?

**Comment by xiaoxiangmoe** [comment]
@znck any update?

**Comment by znck** [comment]
https://github.com/vuejs/vetur/issues/2016

**Comment by mariusa** [comment]
Would you please consider publishing vscode extension in vscode marketplace, so we can use it without building the source?

**Comment by xiaoxiangmoe** [comment]
@mariusa The current extension has serious performance problems, it is recommended not to use it now.

**Comment by johnsoncodehk** [comment]
I am building a tool to provide typescript support for my web project. Someone suggested that I have a look at this project. Some status descriptions of this project would be helpful.

This is my tool:
https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar

**Comment by znck** [comment]
The project is in validation phase. I'm trying to provide refactoring support in stage 1 as that would improve vetur feature set significantly.

**Comment by znck** [comment]
The approach is matching all the expectations. So, this would be actively maintained. Targeting the first release in November.

**Comment by xiaoxiangmoe** [comment]
@znck Should I use vuedx or vetur? What is the relationship between vuedx and vetur?

**Comment by znck** [comment]
VTI and TS plugin are two approaches we've been trying to improve typescript support in IDEs. Since TS plugin uses Vue 3 compiler internally supporting Vue 2 is somewhat difficult. So both are going to stay for a while. TS plugin has option to disable certain features (already present in VTI) so that it can be used in vetur. 

The primary focus of this project would be enabling TS server features for Vue, adding to vetur is secondary and optional.
