### ISSUE TITLE
Auto complete on the template is not working

### ISSUE THREAD

**Issue by pikax** [znck/vue-developer-experience#51]
The info works but not auto-complete, either for attributes or for expressions

![image](https://user-images.githubusercontent.com/4620458/98252192-8b135e80-1f71-11eb-97b5-788f089633e9.png)

**Comment by znck** [comment]
For auto-complete to work, we need to find the correct position in the TSX render function for the cursor position. There are many edge-cases for this. (similar precise mapping is required for renaming and refactoring too)

Earlier I tried using source-map but it didn't work because the generated code is not linear in some cases (eg. `v-if` and `v-for`). Maybe it's worth trying source-map again as the new compilation strategy is somewhat different.

If you're interested in looking into this, look at `compiler-tsx` and `vue-virtual-textdocument` test suites.

**Comment by znck** [comment]
I implemented the source-map support in #60. @pikax can you try this again?

**Comment by znck** [comment]
https://github.com/znck/vue-developer-experience/blob/master/test/baseline/completions.spec.ts covers many completions cases. Closing this. Please open specific issues with a small repro.
